insert into configuration_type (id,name) values (1,'TYPE1');
insert into configuration_type (id,name) values (2,'TYPE2');
insert into configuration_type (id,name) values (3,'TYPE3');
insert into configuration_type (id,name) values (4,'TYPE4');

insert into configuration (scope, name, fk_type, value) values (1,'config name', 1,1);
insert into configuration (scope, name, fk_type, value) values (2,'config name', 2,2);
insert into configuration (scope, name, fk_type, value) values (3,'config name', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 4', 1,4);
insert into configuration (scope, name, fk_type, value) values (5,'config name 5', 1,1);
insert into configuration (scope, name, fk_type, value) values (6,'config name 6', 2,2);
insert into configuration (scope, name, fk_type, value) values (3,'config name 7', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 8', 1,4);
insert into configuration (scope, name, fk_type, value) values (1,'config name 9', 1,1);
insert into configuration (scope, name, fk_type, value) values (2,'config name 10', 2,2);
insert into configuration (scope, name, fk_type, value) values (3,'config name 11', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 12', 1,4);
insert into configuration (scope, name, fk_type, value) values (3,'config name 7', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 8', 1,4);
insert into configuration (scope, name, fk_type, value) values (1,'config name 9', 1,1);
insert into configuration (scope, name, fk_type, value) values (2,'config name 10', 2,2);
insert into configuration (scope, name, fk_type, value) values (3,'config name 11', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 12', 1,4);
insert into configuration (scope, name, fk_type, value) values (3,'config name 7', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 8', 1,4);
insert into configuration (scope, name, fk_type, value) values (1,'config name 9', 1,1);
insert into configuration (scope, name, fk_type, value) values (2,'config name 10', 2,2);
insert into configuration (scope, name, fk_type, value) values (3,'config name 11', 1,3);
insert into configuration (scope, name, fk_type, value) values (4,'config name 12', 1,4);
